[build]
  command = "python3 sitemap.py"
  publish = "/"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
